### ISSUE TITLE
Blueprint Paths to support windows

### ISSUE THREAD

**Issue by reecebrend** [wmfs/flobot#6]
Blueprint paths need to use https://www.npmjs.com/package/upath

**Comment by timneedham** [comment]
Looked into it, if the `\` characters in Windows-style paths are escaped then it works, e.g:

`c:\\blueprint\\my-blueprint`

but:

`c:\blueprints\my-blueprint` will fail silently fail, which isn't great.

So as suggested, using `upath` might be a good improvement, but warning of "invalid"  blueprint paths will also help.
